version: '2'
services:
    pruebaazielv2-app:
        image: pruebaazielv2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://pruebaazielv2-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pruebaazielv2-mssql:
        extends:
            file: mssql.yml
            service: pruebaazielv2-mssql
